In [8]:
import numpy as np

In [9]:
match = 2
gap = -1
mismatch = -1

seq1='CATGT'
seq2='ACGCTG'

#match = 1
#gap = -1
#mismatch = -1
## Test Case 2
#seq1='TTCATA'
#seq2='TGCTCGTA'

In [10]:
def initializeMatrix(seq1,seq2):
    len1 = len(seq1)
    len2 = len(seq2) 
    # Structure Scoring Matrix
    score_matrix = np.zeros((len1+1, len2+1), dtype=int)

    # Initialize all with 0
    score_matrix[0][0] = 0
    return score_matrix,len1,len2


In [11]:
## Setting scores for the diagonal. (match or mismatch)
def Alignment(i,j):
    if i == j:
        return match
    elif i != j:
        return mismatch

In [12]:
def getMaxNeigbour (seq1,seq2,k,l,score_matrix):
    ## Check Max of the 3 neighbours
    diagonal = score_matrix[k-1][l-1] + Alignment(seq1[k-1],seq2[l-1]) ## Mismatch or Match
    horizontal_gap = score_matrix[k][l-1] + gap
    vertical_gap = score_matrix[k-1][l] + gap
    maxNeighbour = max( diagonal , horizontal_gap , vertical_gap )
    return maxNeighbour

In [13]:
def fillMatrix(seq1,seq2):
    
    score_matrix,len1,len2 = initializeMatrix(seq1,seq2)
    # Initialize first row and column with gaps * indices
    for i in range(0,len1+1):
        score_matrix[i][0] = i * gap 
    for j in range(0,len2+1):
        score_matrix[0][j] = j * gap 
        
    # Fill the rest of the matrix based on the neighbours and select max value
    for k in range(1,len1+1):
        for l in range(1,len2+1):
            # Check 3 neighbours (horizontal, vertical and diagonal) 
            maxNeighbour = getMaxNeigbour(seq1,seq2,k,l,score_matrix)
            # Max of the 3 neighbours is put to the score matrix
            score_matrix[k][l] = maxNeighbour
    return score_matrix

In [14]:
score_matrix = fillMatrix(seq1,seq2)

In [15]:
Side_Alignment=""
Top_Alignment=""
i=len(seq1)
j=len(seq2)

while (i > 0 or j > 0):
    diagonal = score_matrix[i - 1][j - 1]  ## Mismatch or Match
    top = score_matrix[i - 1][j]
    left = score_matrix[i][j - 1]
    maxVal = max(diagonal,top,left)
    
    ## Check if the max score neighbour is in the diagonal whether a mismatch or a match
    if ((i > 0 and j > 0) and ((seq1[i - 1] == seq2[j - 1]) or maxVal == diagonal)): # Match or Mismatch

        Side_Alignment = seq1[i - 1] + Side_Alignment
        Top_Alignment = seq2[j - 1] + Top_Alignment
        i = i - 1
        j = j - 1
        
    ## Max Score Neighbour forms a horizontal gap
    elif (i > 0 and (maxVal == top)):
        # Horizontal Gap
        Top_Alignment = "-" + Top_Alignment
        Side_Alignment = seq1[i - 1] + Side_Alignment
        i = i - 1
        
    ## Max Score Neighbour forms a vertical gap    
    elif (j > 0):
        # Vertical Gap
        Top_Alignment = seq2[j - 1] + Top_Alignment
        Side_Alignment = "-" + Side_Alignment
        j = j - 1


In [16]:
print(score_matrix)
print("Seq1: ",seq1)
print("Seq2: ",seq2)

[[ 0 -1 -2 -3 -4 -5 -6]
 [-1 -1  1  0 -1 -2 -3]
 [-2  1  0  0 -1 -2 -3]
 [-3  0  0 -1 -1  1  0]
 [-4 -1 -1  2  1  0  3]
 [-5 -2 -2  1  1  3  2]]
Seq1:  CATGT
Seq2:  ACGCTG


In [17]:
print ("Top_Alignment =",Top_Alignment) ## Sequence 2

Top_Alignment = ACGCTG-


In [18]:
print ("Side_Alignment =",Side_Alignment) ## Sequence 1

Side_Alignment = -C-ATGT
