In [39]:
import numpy as np

In [40]:
match = 5
gap = -6
mismatch = -2

seq1='TTCATA'
seq2='TGCTCGTA'

## Test Case 2 
#match = 3
#gap = -2
#mismatch = -3

#seq1='GGTTGACTA'
#seq2='TGTTACGG'

In [41]:
def initializeMatrix(seq1,seq2):
    len1 = len(seq1)
    len2 = len(seq2) 
    # Structure Scoring Matrix
    score_matrix = np.zeros((len1+1, len2+1), dtype=int)

    # Initialize all with 0
    score_matrix[0][0] = 0
    return score_matrix,len1,len2

In [42]:
## Setting scores for the diagonal. (match or mismatch)
def Alignment(i,j):
    if i == j:
        return match
    elif i != j:
        return mismatch

In [43]:
def getMaxNeigbour (k,l,score_matrix):
    ## Check Max of the 3 neighbours
    diagonal = score_matrix[k-1][l-1] + Alignment(seq1[k-1],seq2[l-1]) ## Mismatch or Match
    horizontal_gap = score_matrix[k][l-1] + gap
    vertical_gap = score_matrix[k-1][l] + gap
    maxNeighbour = max(diagonal, horizontal_gap, vertical_gap, 0)
    return maxNeighbour

In [44]:
def fillMatrix(seq1,seq2):
    
    score_matrix,len1,len2 = initializeMatrix(seq1,seq2)
    
    # Fill the rest of the matrix based on the neighbours and select max value
    for k in range(1,len1+1):
        for l in range(1,len2+1):
            # Check 3 neighbours (horizontal, vertical and diagonal) 
            maxNeighbour = getMaxNeigbour(k,l,score_matrix)
            # Max of the 3 neighbours is put to the score matrix
            score_matrix[k][l] = maxNeighbour
    return score_matrix

In [45]:
score_matrix = fillMatrix(seq1,seq2)

In [46]:
Side_Alignment="" ## Sequence 1
Top_Alignment="" ## Sequence 2

## Get Indices of max value in the matrix (Alignment starts from max score)
max_i,max_j = np.where(score_matrix == np.amax(score_matrix))
i = max_i[0]
j = max_j[0]

## Stop when the Alignment when 0 is found.
while (score_matrix[i][j] != 0):
    diagonal = score_matrix[i - 1][j - 1]  ## Mismatch or Match
    top = score_matrix[i - 1][j]
    left = score_matrix[i][j - 1]
    maxVal = max(diagonal,top,left)
    
    ## Check if the max score neighbour is in the diagonal whether a mismatch or a match
    if ((i > 0 and j > 0) and ((seq1[i - 1] == seq2[j - 1]) or maxVal == diagonal)): # Match or Mismatch

        Side_Alignment = seq1[i - 1] + Side_Alignment
        Top_Alignment = seq2[j - 1] + Top_Alignment
        i = i - 1
        j = j - 1
    ## Max Score Neighbour forms a horizontal gap
    elif (i > 0 and (maxVal == top)):
        # Horizontal Gap
        Top_Alignment = "-" + Top_Alignment
        Side_Alignment = seq1[i - 1] + Side_Alignment
        i = i - 1
    ## Max Score Neighbour forms a vertical gap   
    elif (j > 0):
        # Vertical Gap
        Top_Alignment = seq2[j - 1] + Top_Alignment
        Side_Alignment = "-" + Side_Alignment
        j = j - 1


In [47]:
print(score_matrix)
print ("Seq 1: ", seq1)
print ("Seq 2: ", seq2)

[[ 0  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  5  0  0  5  0]
 [ 0  5  3  0  5  3  0  5  3]
 [ 0  0  3  8  2 10  4  0  3]
 [ 0  0  0  2  6  4  8  2  5]
 [ 0  5  0  0  7  4  2 13  7]
 [ 0  0  3  0  1  5  2  7 18]]
Seq 1:  TTCATA
Seq 2:  TGCTCGTA


In [48]:
print ("Top_Alignment =",Top_Alignment) ## Sequence 2

Top_Alignment = TCGTA


In [49]:
print ("Side_Alignment =",Side_Alignment) ## Sequence 1

Side_Alignment = TCATA
